### ISSUE TITLE
Associate search validation

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#1]
**Summary:**
When looking for Associates, the validation is too strict. Literally, one field should be the only requirement. WSIB checkbox should be optional, and phone number should not be required.
http://london.o55.me/en/associate/search
![screen shot 2018-02-18 at 12 36 39 pm](https://user-images.githubusercontent.com/7537946/36354870-6b8d76f8-14a8-11e8-93b7-46e42402429d.png)

**Comment by bartmika** [comment]
Hi @KPSbuttar,

To modify any GUI in this project, you can go to the following directory root and look in here: https://github.com/over55/overfiftyfive-django/tree/master/overfiftyfive/templates

**Comment by bartmika** [comment]
@KPSbuttar - Note: This problem exists in this file https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/templates/tenant_associate/search/search_view.html

**Comment by KPSbuttar** [comment]
Hi sir, @rodolfomartinez This is already fixed found latest UI codes here so all done. Will finish all other now.
Thanks
