### ISSUE TITLE
logout gives 404

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#10]
got this when logging out (I had been logged in for quite some time)
![67df0e24-dc23-47bc-b3d4-d23b5c4746dc](https://user-images.githubusercontent.com/7537946/38430179-855511f8-398e-11e8-9f2c-41794acbcda7.png)

**Comment by bartmika** [comment]
@rodolfomartinez I confirm I have received this before but I believe I patched it up. May you please clear your browsers cache, retry again and see if this happens again?

**Comment by bartmika** [comment]
Hey @rodolfo-over55, may I know the status of this issue?
