### ISSUE TITLE
Remove extra text - Edit Member

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#100]
**Summary:**
For this URL
Remove the text that I have stroked in red. It is not needed here.
![0789167c-a4ec-4af6-aed3-6c6691162629](https://user-images.githubusercontent.com/7537946/39557752-e0d739e2-4e57-11e8-9df1-fda759e39857.jpeg)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done
