### ISSUE TITLE
Remove Extra Text - Edit Client

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#101]
**Summary:**
At this URL http://london.o55.me/en/clients/summary/detail/23060/edit/

remove the extra text stroked in red.
![d97d2404-2400-4dda-aa0e-d0b8aed9e1f2](https://user-images.githubusercontent.com/7537946/39557816-557c200a-4e58-11e8-82c7-f865ec0f4a9b.jpeg)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done
