### ISSUE TITLE
Add Away Announcement Page 

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#113]
**Summary:**
At this URL http://london.o55.me/en/settings/awaylog/create/

change title to "Add Announcement" and remove the text marked in red in this image

![e1285f9d-9974-4f51-84a9-b1e802025397](https://user-images.githubusercontent.com/7537946/39609547-cae620a6-4f17-11e8-9a6c-7f0f8c799b8b.jpeg)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done
