### ISSUE TITLE
Add Residential Client

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#114]
**Summary:**
At this URL
http://london.o55.me/en/clients/create/residential
for adding residential clients, please remove the text marked in red
![5f8c9c92-72e8-4a7a-9579-19820a490c02](https://user-images.githubusercontent.com/7537946/39609703-df3aee6e-4f18-11e8-8063-be0b16ed86cb.jpeg)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done
