### ISSUE TITLE
Add Commercial Client 

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#116]
**Summary:**
At this URL http://london.o55.me/en/clients/create/commercial
 please remove the text marked in red 
![c34a9fca-465a-4e55-b7f6-13fe32571af1](https://user-images.githubusercontent.com/7537946/39609831-d4c5856a-4f19-11e8-89b8-8fa141b632e1.jpeg)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir!
