### ISSUE TITLE
Passwords too short?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#118]
**Summary:**
On the password section for adding members etc., it states that passwords must be 5 characters in length. Is this the case or a typo?

**Comment by rodolfomartinez** [comment]
When I tried to add someone with a 5 character password got a message that it should be at least 10. Can we settle on 8?
![556a2d2d-58fe-4169-90b9-f1a6badfaf9e](https://user-images.githubusercontent.com/7537946/39610236-eb6f5658-4f1c-11e8-87e4-2ef1dc6e453f.png)

**Comment by bartmika** [comment]
Okay I lowered the value to 8.
