### ISSUE TITLE
Task Close

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#135]

**Comment by bartmika** [comment]
@rodolfomartinez Can you confirm this is good GUI?

# Current Page
![screen shot 2018-05-06 at 10 44 37 am](https://user-images.githubusercontent.com/5767602/39674483-9e65200e-511a-11e8-8e1c-ab59d2d4006b.png)

# Other Option Selected
![screen shot 2018-05-06 at 10 44 50 am](https://user-images.githubusercontent.com/5767602/39674486-a764efb8-511a-11e8-89ca-1e295ffc442e.png)

# The List of Options
![screen shot 2018-05-06 at 10 45 00 am](https://user-images.githubusercontent.com/5767602/39674490-b0d692f4-511a-11e8-9994-ed5b81046c9f.png)

**Comment by rodolfomartinez** [comment]
looks good to me
