### ISSUE TITLE
"Associate -> Edit" - Country & Provinces errors locally

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#146]
When I try editing an associate on my local machine, I get the following javascript code, may you please investigate why this error message is occuring and fix the JavaScript code?

![screen shot 2018-05-06 at 6 56 07 pm](https://user-images.githubusercontent.com/5767602/39678705-4e9ed7fa-515f-11e8-824c-e30832276e1f.png)

![screen shot 2018-05-06 at 6 55 40 pm](https://user-images.githubusercontent.com/5767602/39678707-5414afde-515f-11e8-9853-af920da38cfb.png)

@rodolfomartinez FYI

**Comment by bartmika** [comment]
@KPSbuttar Just a follow up on this issue. I tried **adding** an associate and the provinces/country dropdown is confirmed working. So the problem is only with the **update**.

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir, this is done.
