### ISSUE TITLE
Edit Job - Customer field and Associate Field - undefined undefined

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#147]
**Summary:**
When editing a job, he customer field and the Associate Fields are still editable and gives "undefined undefined". These should be read only.

**Comment by bartmika** [comment]
@rodolfomartinez Hey Rodolfo, this might be a duplicate issue. Remember how we are going to disable the Job edit page? If we disable this page then this issue will not be a problem. How should we proceed?
