### ISSUE TITLE
500 when searching

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#154]
**Summary:**
At this URL
http://london.o55.me/en/members/search/results/?given_name=&last_name=bisschop&telephone=&email_id=

when doing advanced member search usiong lastname "biscchop" I received an error 500

![aa58d195-7193-4ba1-985a-edce60d79711](https://user-images.githubusercontent.com/7537946/39774495-02c024a4-52c9-11e8-885a-16a63054b6c7.png)

**Comment by bartmika** [comment]
Issue fixed.
