### ISSUE TITLE
Adding Commercial Client > Phone

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#16]
**Summary:**
The placement of the phone type makes it a bit difficult to understand what must happen. Can we please default this to type = "Work" so that it passes validation easier? If the user wants, they can always change later.

**Comment by bartmika** [comment]
Hi @KPSbuttar, this looks like to be somesort of CSS error, may you please look at this? Thanks!

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez This is done please REVIEW after you redeploy server for all updates to go live. I guess it will get fixed but we need to check live. Thanks!

**Comment by bartmika** [comment]
![screen shot 2018-04-27 at 11 49 48 pm](https://user-images.githubusercontent.com/5767602/39391702-da56f44e-4a75-11e8-97a4-5ce62dff2d0f.png)

Hi @KPSbuttar I reviewed and I still get the error. Here is what I see. I am using Google Chrome. May you please investigate?

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its done hope it will work this time. Thanks
