### ISSUE TITLE
Disallowed Host - related to logout from HTTP vs HTTPS?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#165]
**Summary:**
Received this when logging out using http - should we use https redirect? ie all http://workery.ca requests go to https? Otherwise I receive this error
URL: https://*.workery.ca/en/logout/redirector
![088194fe-5d1c-4fa1-94a3-b310296adfbf](https://user-images.githubusercontent.com/7537946/39953776-d097c080-5580-11e8-904e-93dc93dc49fd.png)

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, this is happening because you did not clear your cache. May you please clear your cache / cookies and try again. I confirm I got this until I cleared my cache and I could not get this error again.

**Comment by rodolfomartinez** [comment]
OK confirmed. Thanks
