### ISSUE TITLE
Add Member/Client - DOB

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#22]
**Summary:**

It is possible to future date DOB during registration - ie I can say that I will be born 1 week from now. Not a huge deal, but if correct this remember that assigning of tasks, etc. will be able to happen in the future

**Comment by bartmika** [comment]
Hi @KPSbuttar,

To modify any GUI in this project, you can go to the following directory root and look in here: https://github.com/over55/overfiftyfive-django/tree/master/overfiftyfive/templates

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Please explain this issue. I didn't understood what to do exactly here.
Reply ASAP!!

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir, All DOB fields in all pages are fixed. Thanks
