### ISSUE TITLE
GUI: Select Radio validation error message

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#34]
![screen shot 2018-04-14 at 5 35 41 pm](https://user-images.githubusercontent.com/5767602/38772667-5e1d661c-400a-11e8-882d-2341e9885d2d.png)

When you add/update a customer (or associate or staff) and do not select a radio button then an alert message appears. Please update the GUI for all the pages to support this in-browser validation (and not alert).

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez This is done can you please review at the frontend website just to confirm as i can't access over55 website to check all errors. please provide me that links to check live anyways its done. thanks
