### ISSUE TITLE
Job - Search

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#35]
Please fix the GUI so the listed items are not single items on row but have multiple column items.

`http://london.o55.me/en/jobs/create/step-1/search-results?given_name=John&last_name=&telephone=`

**Comment by KPSbuttar** [comment]
@bartmika which is the file related to this UI can you please share path to that template file.
@rodolfomartinez Also sir for this issue you mean to implement this UI template fix which i did here: http://inthought.pw/clients/client_add_1.html
Please check and reply asap.

Thanks

**Comment by bartmika** [comment]
@KPSbuttar - https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/templates/tenant_order/create/step_1_a_2_search_results_view.html
