### ISSUE TITLE
Confirm Deletion of Tag/Skill Set

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#37]
**Summary:**
Skills and tags can be deleted easily and without alerts. There needs to be a prompt like -

WARNING: you are about to PERMANENTLY delete this item - this action CANNOT BE UNDONE. Do you want to continue?
Yes/No

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, may you please implement? This is pure JS/CSS code. You can find the code in this file:

https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/templates/tenant_setting/skill_set/list_view.html

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir this is done i have added Yes/No Modal but we need to review at live site. Please message me when you redeploy so all codes get live. Thanks!
