### ISSUE TITLE
Jobs: Validation on "Search" or "Add" page

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#4]
![screen shot 2018-04-02 at 7 49 50 pm](https://user-images.githubusercontent.com/5767602/38221746-21b723f2-36af-11e8-84da-cec04375e1df.png)

**Comment by bartmika** [comment]
@KPSbuttar This is a GUI issue which has CSS/JS related. You can modify this file for this issue: https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/templates/tenant_order/search/search_view.html

**Comment by bartmika** [comment]
1. Go to page
2. Click “search”. (do not write anything)
3. You will get error as a pop up alert. Our goal is to have error messages inside the page as we handled it elsewhere.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Both search view and add or search pages are updated and fixed. Please review at the front end website if all works fine. 
Thanks

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez  This issue is fixed in all UI for members, jobs and clients.
