### ISSUE TITLE
Cannot search by job #?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#42]
**Summary:**
Job number does not appear to work when searching for jobs

**Comment by bartmika** [comment]
Correct, searching by text and integers in a database are two separate functions. Currently I am using the `postgresql` native searching but if we want to do more advanced searching as this ticket I'll need to re-write searching to use something more advanced like `django-haystack` library. I will implement but it will slightly delay us.

**Comment by bartmika** [comment]
Ended up not using `django-haystack but instead just a native solution using `postgresql`.
