### ISSUE TITLE
Member Active/Inactive Status

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#44]
**Summary:**
Need a way to set status of members to active/inactive - could be as simple as a Radio button with
Active / Inactive on the edit page

**Comment by bartmika** [comment]
![screen shot 2018-04-17 at 8 11 05 pm](https://user-images.githubusercontent.com/5767602/38904978-88bf5b5a-427b-11e8-90a8-c1673c59fbf2.png)

Implemented activated / inactivated status.
