### ISSUE TITLE
Jobs: "Email" searching in "Create Job"

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#5]
Look into why this is problematic.

**Comment by bartmika** [comment]
@KPSbuttar - Please integrate the email searching for this page https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/templates/tenant_order/search/search_view.html

**Comment by KPSbuttar** [comment]
@bartmika Hi sir can you please send me frontend website url to this page so i can review whats the Problem with this page codes, also can you explain a bit what issues you facing with this page UI.
Reply ASAP! Thanks

**Comment by bartmika** [comment]
@KPSbuttar - the problem is I cannot get the “email” field integrated with your (1) validation (2) submit JavaScript code. Can you update that template so it will work?

URL is http://o55.me/en/login and use your assigned credentials.

**Comment by bartmika** [comment]
@KPSbuttar FYI - Just redeployed the server with your latest code so you can see on the main server your change. Next redeploy won't happen for approx. 24 hours from now. Thanks!

**Comment by KPSbuttar** [comment]
@bartmika Ok thank you sir
But i can't login here http://o55.me/en/login with credentials you given, can you please recheck.

**Comment by KPSbuttar** [comment]
@bartmika Ok sir i just logged IN, got login details. Thanks

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir This is fixed for Clients, members and jobs pages. Also have integrated Email in search view and fixed existing client search before add. 
Please review all UI is fixed. Check if all working fine at front-end.
