### ISSUE TITLE
Job Search - "Email" not required.

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#50]
When I want to ONLY search for customer name, it asks for me to input an email. This is not correct, please remove the required option.

![screen shot 2018-04-21 at 5 51 01 pm](https://user-images.githubusercontent.com/5767602/39089089-b6b364f2-458c-11e8-8a25-d05e36cbae22.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez This is done sir.
