### ISSUE TITLE
Settings > Buttons

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#53]
**Summary:**
At this URL (and similar ones) http://london.o55.me/en/settings/
Need the buttons to work - right now clicking them does nothing
![761025c3-adf9-4935-a326-bc124e184f6b](https://user-images.githubusercontent.com/7537946/39162426-71a13958-4743-11e8-88fc-42469a15214a.jpeg)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir these buttons are working fine please recheck. Thanks!
