### ISSUE TITLE
Announcements Settings - GUI Fixes

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#55]
The following GUI elements need to be fixed.

# Create
## File
https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/templates/tenant_setting/awaylog/create_view.html

## TODO
* `Associates` field starts as "undefined undefined", it should say something like "Please select an associate".

* The `Reason (Other)` field needs to be hidden and only appear when "Other" option is selected in the `Reason` field.

* Validation needs improvement

# Update
## FIle
https://github.com/over55/overfiftyfive-django/blob/master/overfiftyfive/templates/tenant_setting/awaylog/update_view.html

## TODO
* Associates field starts as "undefined undefined", it should say something like "Please select an associate".

* The `Reason (Other)` field needs to be hidden and only appear when "Other" option is selected in the `Reason` field.

* Validation needs improvement

**Comment by bartmika** [comment]
@rodolfomartinez FYI

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir, Both pages are done. Please redeploy server so i can review all progress. thanks
