### ISSUE TITLE
Add more buttons to header of page - Update globally

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#63]
Make sure there exists:

* back

* view comments

* edit

**Comment by rodolfomartinez** [comment]
Something like this:
![60ea1451-d0e5-4dc7-94d2-f7a2d5f39a2d](https://user-images.githubusercontent.com/7537946/39397843-bd365c20-4ad3-11e8-9cfd-a29c88cc7ca5.jpeg)

**Comment by bartmika** [comment]
Updated according to @rodolfomartinez specs.
