### ISSUE TITLE
Announcements - Select Associate - undefined undefined

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#65]
**Summary:**
When this screen first loads, the Associate list says "undefined undefined" - can it load blank?

![f1ef5b25-f443-4e55-a7f3-f4a0933dbae2](https://user-images.githubusercontent.com/7537946/39396803-1a3ad5f6-4ac3-11e8-8104-28d553f5232b.png)

**Comment by rodolfomartinez** [comment]
@KPSbuttar Can you please make sure that an Associate MUST be selected as part of validation? Currently, with this "undefined undefined" error it is possible to have an announcement that has no Associate Member

**Comment by KPSbuttar** [comment]
@rodolfomartinez Sir, Its done please redeploy server so i can check all tickets progress. Including Country dropdown etc.
