### ISSUE TITLE
Add Announcement - Reasons

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#66]
**Summary:**

The reason text box is always visible, it should only populate when "Other" is chosen from the dropdown above, and should hide dynamically if Other is selected and then something else is selected
![b3b9c5ff-2984-4f60-84a2-7fe98605a7f5](https://user-images.githubusercontent.com/7537946/39396815-4eb7de0a-4ac3-11e8-8b2a-b0568529f8c9.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez This is done.
