### ISSUE TITLE
Dashboard - center circles

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#71]
**Summary:**
On the dashboard, please center align the three circles. See screencap

![2618fb1a-48fc-4903-9b6a-e3ed442f9983](https://user-images.githubusercontent.com/7537946/39396874-57ca9cd4-4ac4-11e8-8c77-d7e42be6dafb.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez If you want to remove tasks and need to have 3 circles only then reassign me will center all. thanks

**Comment by rodolfomartinez** [comment]
@KPSbuttar - please apply to pages like this, which only have 3 circles
http://london.o55.me/en/jobs/summary/

**Comment by KPSbuttar** [comment]
@rodolfomartinez All pages are done.
