### ISSUE TITLE
Dashboard - Member Count

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#72]
**Summary:**
On the dashboard, the member circle should only count Active Members (the current count seems very high). Also, please rename it to
"Active Members" 

If need be, maybe we should create the member data from scratch and ignore the Access ETL data?

**Comment by bartmika** [comment]
@rodolfomartinez I renamed as specificed.

It appears that we have 3032 active members and a total of 3367 members. Perhaps this is something you and your team can modify post launch of the project?
