### ISSUE TITLE
Cannot add member - Country dropdown blank

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#76]
**Summary:**
When adding a member, the country dropdown is blank, and no options appear

![0a4a2c58-383d-49ff-bec8-2f4c4332d097](https://user-images.githubusercontent.com/7537946/39397132-367f9724-4ac8-11e8-97dc-b5428b740c90.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir I guess #24 FIX will make this ticket complete as well. Thanks
