### ISSUE TITLE
Job imported with comment dated today?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#77]
**Summary:**
A previous job was a comment with today's date at 3:35AM. Is this a result of the ETL, left over Access data, or both?
http://london.o55.me/en/jobs/summary/detail/23283/comments/

![b2fe5a22-d8db-41cb-b712-d6ee7651c55f](https://user-images.githubusercontent.com/7537946/39397145-785e68fa-4ac8-11e8-8067-d49d33b9dca6.png)

**Comment by bartmika** [comment]
@rodolfomartinez Great find! Unfortunately this is something created by the ETL, the records do not have datetime associated with the comment and the system is forced to input todays date. I don't really know how to handle this issue besides this:

* If comment has no user, this means it's the system, so we will override the datetime to some sort of text like "Past Date" and name to be "Legacy Importer.

What do you think of this?

**Comment by rodolfomartinez** [comment]
@bartmika - let's just leave it as is.
