### ISSUE TITLE
Announcements Display on Dashboard

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#84]
![3291a89c-0440-4356-abf8-875cf7d24fc0](https://user-images.githubusercontent.com/7537946/39456697-80690f4c-4cb6-11e8-94e9-bcc872574c73.png)
**Summary:**
On the dashboard page, announcements currently display as in the image below.  Instead, can we display in one row, in the following format:

<Associate Member Name in bold> <item from reason dropdown - normal> <Away Until - bold> <date - bold>

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir. Please check design, if all ok. Thanks
