### ISSUE TITLE
Logo too big

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#86]
@rodolfomartinez @KPSbuttar The logo is wayyyy to big when you log into the app.

![screen shot 2018-05-01 at 7 04 16 pm](https://user-images.githubusercontent.com/5767602/39497712-94d337ca-4d72-11e8-9bd1-93dc28d2e12c.png)

**Comment by rodolfomartinez** [comment]
@KPSbuttar to clarify this is once you are logged in to the system, the logo that was supposed to replace the text Over 55 in the top left. Also, this is the wrong image. It should be this one, and please make sure it is small - approx 300 x75 or something like that

@bartmika FYI

![5ab8ed88-0a06-4962-9c3c-b5e6821a75c2](https://user-images.githubusercontent.com/7537946/39498559-d48dccfa-4d76-11e8-810f-610637b17247.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir its done

**Comment by bartmika** [comment]
![screen shot 2018-05-02 at 8 00 05 pm](https://user-images.githubusercontent.com/5767602/39554902-740dadf0-4e43-11e8-8322-d21adcbd6a5b.png)

Confirmed
