### ISSUE TITLE
Customer -> Add Commercial Customer -> Provinces do not work

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#88]
@rodolfomartinez @KPSbuttar 

![screen shot 2018-05-01 at 7 08 56 pm](https://user-images.githubusercontent.com/5767602/39497873-34fd7134-4d73-11e8-8b57-36132e34ead5.png)

**Comment by KPSbuttar** [comment]
HI sir, Its fixed with #24 issue fix.
