### ISSUE TITLE
Customer -> Add Commercial Customer -> Other Phone Type not working

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#89]
@rodolfomartinez @KPSbuttar 

![screen shot 2018-05-01 at 7 10 57 pm](https://user-images.githubusercontent.com/5767602/39497976-a56a63aa-4d73-11e8-82dc-8813a3a3932b.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir, This is fixed.
