### ISSUE TITLE
Associates -> Add Associate -> Skillset CSS Issue

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#91]
@rodolfomartinez @KPSbuttar 
Most recent commit has caused some-sort of CSS styling issue.

![screen shot 2018-05-01 at 7 16 04 pm](https://user-images.githubusercontent.com/5767602/39498092-3fc6bb38-4d74-11e8-8a5d-fa82c0bcf05a.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir this is already fixed.
