### ISSUE TITLE
Associate -> Add Associate -> Country does not work

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#92]
@rodolfomartinez @KPSbuttar 

![screen shot 2018-05-01 at 7 17 52 pm](https://user-images.githubusercontent.com/5767602/39498153-70f65ede-4d74-11e8-9a8b-c9e4d6af261b.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez  Its done.
