### ISSUE TITLE
Job -> Add Job -> Page 4 -> Skill Sets CSS Styling

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#94]
@rodolfomartinez @KPSbuttar 

Please fix the styling.

![screen shot 2018-05-01 at 7 23 47 pm](https://user-images.githubusercontent.com/5767602/39498297-5858188a-4d75-11e8-9f12-c0bdd4f19439.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its fixed sir.
