### ISSUE TITLE
Job -> Edit Job -> Associates/Customers still "undefined" for select2

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#95]
@rodolfomartinez @KPSbuttar 

And here is customer.

![screen shot 2018-05-01 at 7 27 00 pm](https://user-images.githubusercontent.com/5767602/39498389-d74f7534-4d75-11e8-852e-c9305b87381c.png)

And here is associate.

![screen shot 2018-05-01 at 7 29 01 pm](https://user-images.githubusercontent.com/5767602/39498435-0836adf2-4d76-11e8-9792-704d7a3c727d.png)

Also CSS styling is wrong for skill sets.

**Comment by rodolfomartinez** [comment]
@bartmika - the customer should not be editable, even in edit mode, since the job is tied to a customer. Can we keep this as read only

**Comment by bartmika** [comment]
@rodolfomartinez You are correct, as a result, @KPSbuttar does not need to do this task. I will close this ticket and make the job update no longer possible.
