### ISSUE TITLE
Assign Form

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#97]
**Summary:**
At this URL
http://london.o55.me/en/jobs/summary/detail/23284/activity-sheet/create?associate_id=6120

![7ea2b367-c3f1-4af4-8062-68e4c4a5d5b9](https://user-images.githubusercontent.com/7537946/39557501-12dcfe24-4e56-11e8-9009-64f52367919f.png)

Can we update the button to say Update instead of Assign,
and in the Comment box can the sample text be
"Add a comment"
instead of 
How here...

**Comment by KPSbuttar** [comment]
@rodolfomartinez Please clarify with correct Links i thing that activity page is updated with new table.
