### ISSUE TITLE
Job Activity Sheet

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#98]
**Summary:**
At this URL
http://london.o55.me/en/jobs/summary/detail/23288/activity-sheet/
Can we rename the column
"Has Accepted?"
to
"Accepted?"

and instead of true false, Yes, No
If no, should be normal, but if yes, bold

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir column name updated BUT for "yes/no" normal and bold can you show me page with activities recorded in table and activity create/input page how activity recorded. Reply ASAP

**Comment by rodolfomartinez** [comment]
resolved for now
