### ISSUE TITLE
Cannot update members that do not have email

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/overfiftyfive-django#99]
**Summary:**
At this URL
http://london.o55.me/en/members/summary/detail/6121/edit/
I cannot edit this member, because she does not have an email address, and I cannot add skills or update any info because she will not validate.

I do want all Associates to have email, but some just do not have email. What can we do?

**Comment by bartmika** [comment]
Yes, this is an excellent find!

So here is the situation, 
(1) we have a rule that you cannot submit an associate which does not have an email. 
(2) You want to update a legacy record where an associate did not provide email.
(3) And the system rejects your entry.

What do we do? There's no easy answer here. My recommendation is you call up the associate and get the email.

**Comment by bartmika** [comment]
This issue was discussed between myself and @rodolfomartinez and we concluded we will close this issue by marking it as resolved.
